import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Highlights from "@/components/Highlights";
import FeaturesPage from "@/components/FeaturesPage"
import ReviewPage from "@/components/ReviewPage";
import UpcomingWebinar from "@/components/UpcomingWebinar";
import Instructor from "@/components/Instructor";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="w-full relative flex items-center justify-center">
          <Navbar/>
        </div>
        {children}
        <div className="w-full pt-20 bg-neutral-950 relative flex items-center justify-center">
          <Highlights/>
        </div>
        <div className="w-full bg-neutral-950 relative flex items-center justify-center">
          <FeaturesPage />
        </div>
        <div className="w-full bg-neutral-950 relative flex items-center justify-center">
          <ReviewPage />
        </div>
        <div className="w-full bg-neutral-950 relative flex items-center justify-center">
          <UpcomingWebinar />
        </div>
        <div className="w-full bg-neutral-950 flex items-center justify-center">
          <Instructor />
        </div>
        <div className="w-full bg-neutral-950 flex items-center justify-center">
          <Footer />
        </div>
      </body>
    </html>
  );
}
